apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: true
  containers:
  - name: build-env
    image: compile-ubuntu
    # marking the image as local
    imagePullPolicy: Never
    command: 
    - cat
    tty: true