pipeline {
    agent {
        kubernetes {
            yaml '''
                apiVersion: v1
                kind: Pod
                spec:
                    nodeSelector:
                        node-role.kubernetes.io/worker: true
                    containers:
                    - name: build-env
                      image: compile-ubuntu
                      # marking the image as local
                      imagePullPolicy: Never
                      command: 
                      - cat
                      tty: true
                '''
        }
    }
    stages {
        stage('Compile') {
            steps {
                container('build-env') {
                    sh 'pwd && apt update && apt install -y git clang'
                    sh 'cp -r /workspace/SFML-2.6.0/lib/* /usr/local/lib'
                    sh 'rm -rf /workspace/MyRPGGame && git clone https://github.com/lazarovziv/MyRPGGame.git /workspace/MyRPGGame'
                    sh 'cd /workspace/MyRPGGame'
                    sh 'cmake -B build . && cd build && make'
                }
            }
        }
    }
}