pipeline {
    agent {
        kubernetes {
            yaml '''
                apiVersion: v1
                kind: Pod
                spec:
                    nodeSelector:
                        node-role.kubernetes.io/worker: true
                    containers:
                    - name: build-env
                      image: compile-ubuntu
                      # marking the image as local
                      imagePullPolicy: Never
                      command: 
                      - cat
                      tty: true
                '''
        }
    }
    stages {
        stage('Compile') {
            steps {
                container('build-env') {
                    sh 'apt install -y git'
                    sh 'git clone https://github.com/lazarovziv/MyRPGGame.git'
                    sh 'cd MyRPGGame && cmake -B build . && cd build && make'
                }
            }
        }
    }
}