// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgAPI.Data_Access;

#nullable disable

namespace RpgAPI.Migrations
{
    [DbContext(typeof(RPGGameDBContext))]
    partial class RPGGameDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RpgAPI.Models.GameEntity", b =>
                {
                    b.Property<long>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EntityId"), 1L, 1);

                    b.Property<int>("AttackPoints")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHealthPoints")
                        .HasColumnType("int");

                    b.Property<int>("CurrentManaPoints")
                        .HasColumnType("int");

                    b.Property<int>("DefencePoints")
                        .HasColumnType("int");

                    b.Property<int>("GameMapId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlayer")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHealthPoints")
                        .HasColumnType("int");

                    b.Property<int>("MaxManaPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("NpcEnemyId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<float>("PositionX")
                        .HasColumnType("real");

                    b.Property<float>("PositionY")
                        .HasColumnType("real");

                    b.Property<float>("Speed")
                        .HasColumnType("real");

                    b.HasKey("EntityId");

                    b.HasIndex("GameMapId");

                    b.HasIndex("NpcEnemyId");

                    b.HasIndex("PlayerId");

                    b.ToTable("GameEntities", (string)null);
                });

            modelBuilder.Entity("RpgAPI.Models.GameMap", b =>
                {
                    b.Property<int>("GameMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameMapId"), 1L, 1);

                    b.Property<int>("WorldMapCol")
                        .HasColumnType("int");

                    b.Property<int>("WorldMapRow")
                        .HasColumnType("int");

                    b.HasKey("GameMapId");

                    b.ToTable("GameMaps", (string)null);
                });

            modelBuilder.Entity("RpgAPI.Models.NPCEnemy", b =>
                {
                    b.Property<int>("EnemyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnemyId"), 1L, 1);

                    b.Property<float>("BattleAreaRadius")
                        .HasColumnType("real");

                    b.Property<int>("BattleTimeout")
                        .HasColumnType("int");

                    b.Property<int>("EnemyType")
                        .HasColumnType("int");

                    b.Property<float>("WanderAreaRadius")
                        .HasColumnType("real");

                    b.HasKey("EnemyId");

                    b.ToTable("Enemies", (string)null);
                });

            modelBuilder.Entity("RpgAPI.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"), 1L, 1);

                    b.Property<int>("CriticalPoints")
                        .HasColumnType("int");

                    b.Property<int>("ExpPoints")
                        .HasColumnType("int");

                    b.Property<int>("IntelligencePoints")
                        .HasColumnType("int");

                    b.Property<int>("PlayerType")
                        .HasColumnType("int");

                    b.Property<int>("StrengthPoints")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("RpgAPI.Models.GameEntity", b =>
                {
                    b.HasOne("RpgAPI.Models.GameMap", "GameMap")
                        .WithMany("GameEntity")
                        .HasForeignKey("GameMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgAPI.Models.NPCEnemy", "Enemy")
                        .WithMany("GameEntity")
                        .HasForeignKey("NpcEnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgAPI.Models.Player", "Player")
                        .WithMany("GameEntity")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");

                    b.Navigation("GameMap");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RpgAPI.Models.GameMap", b =>
                {
                    b.Navigation("GameEntity");
                });

            modelBuilder.Entity("RpgAPI.Models.NPCEnemy", b =>
                {
                    b.Navigation("GameEntity");
                });

            modelBuilder.Entity("RpgAPI.Models.Player", b =>
                {
                    b.Navigation("GameEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
