name: Linux Compile and Test

# run if any of the dockerfiles changed
on: [ pull_request, workflow_dispatch ]

jobs:
  linux-compile:
    runs-on: ubuntu-latest
    container:
      image: zivlazarov/rpg:1.3
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    steps:
    - name: Initial checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Compile
      run: cmake -B build/ -G "Ninja" . && cmake --build build/
    
    # upload tests artifact to be used in another job
    - uses: actions/upload-artifact@v4
      with:
        name: tests-artifact
        path: build/bin/tests

  linux-test:
    runs-on: ubuntu-latest
    needs: linux-compile
    container:
      image: zivlazarov/rpg:1.3
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    steps:
    - name: Initial checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
      
    # get tests artifact
    - uses: actions/download-artifact@v4
      with:
        name: tests-artifact
    
    - name: Run tests
      run: chmod +x ./tests && ./tests


    