name: Vulkan Build

on: [ pull_request, workflow_dispatch ]

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: zivlazarov/rpg:1.3
      options: --user root
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive  
    - name: Compile
      run: cmake -D GLFW_BUILD_X11=1 -D GLFW_BUILD_WAYLAND=0 -B MyRPGGame/vulkan/build/ -G "Ninja" MyRPGGame/vulkan/ && cmake --build MyRPGGame/vulkan/build/  
