name: Windows Build

on:
  # run if any of the dockerfiles changed
  pull_request:
    paths:
      - 'dockerfiles/**'
  # run on demand
  workflow_dispatch:

jobs:
  windows-image-build:
    runs-on: windows-latest
    steps:
    - name: Initial checkout
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      id: docker_login

    - name: Build Windows image
      run: docker build -f ./dockerfiles/windows.Dockerfile -t ${{ secrets.IMAGE_NAME }}:${{ secrets.WINDOWS_IMAGE_TAG }} .
      id: docker_build
      if: steps.docker_login.outcome == 'success'

    - name: Push Windows image
      run: docker push ${{ secrets.IMAGE_NAME }}:${{ secrets.WINDOWS_IMAGE_TAG }}
      id: docker_push
      if: steps.docker_build.output == 'success'
    
  windows-build:
    runs-on: windows-latest
    container:
      image: ${{ secrets.IMAGE_NAME }}:${{ secrets.WINDOWS_IMAGE_TAG }}
    steps:
    - name: Initial checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Compile
      run: cmake -B build/ . && cmake --build build/

    # upload tests artifact to be used in another job
    - uses: actions/upload-artifact@v4
      with:
        name: tests-artifact
        path: build/bin/tests
      